version: '3'
services:
  static-rdf-server:
    build: .
    image: ghcr.io/informasjonsforvaltning/static-rdf-server:test
    expose:
      - 5000
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - API_KEY=${API_KEY}
    volumes:
      - ./tests/files/workspace/:/srv/www/static-rdf-server/

  static-rdf-nginx:
    build: nginx/.
    ports:
      - 8080:8080
    volumes:
      - ./tests/files/workspace/:/srv/www/static-rdf-server/
    depends_on:
      - static-rdf-server
