---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../base
  - storage.yaml
patches:
  - target:
      kind: Deployment
      name: static-rdf
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "https://fellesdatakatalog.digdir.no,https://*.fellesdatakatalog.digdir.no,https://data.norge.no,https://data.transportportal.no,https://transportportal.no"
