---
apiVersion: v1
kind: Service
metadata:
  name: static-rdf-server
  labels:
    fdk.service: static-rdf
spec:
  type: ClusterIP
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    fdk.service: static-rdf
