---
apiVersion: v1
kind: Service
metadata:
  name: static-rdf-nginx
  labels:
    fdk.service: static-rdf
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    fdk.service: static-rdf
