name: Deploy to production & demo

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-server:
    name: Build server image
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: static-rdf-server
      environment: prod
      gh_environment: prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-nginx:
    name: Build nginx image
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: static-rdf-nginx
      environment: prod
      gh_environment: prod
      dockerfile: Dockerfile
      build_context: ./nginx/
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    name: Deploy to prod environment
    needs: [build-server, build-nginx]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: static-rdf-server
      environment: prod
      gh_environment: prod
      cluster: digdir-fdk-prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-demo:
    name: Deploy to demo if prod-deploy is successful
    needs: deploy-prod
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: static-rdf-server
      environment: demo
      gh_environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
