name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  run-coverage:
    name: Coverage
    uses: Informasjonsforvaltning/workflows/.github/workflows/coverage-nox.yaml@main
    with:
      python_version: '3.9'
      python_architecture: x64
      sessions: integration_tests
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      API_KEY: ${{ secrets.API_KEY }}

  build-and-deploy-staging:
    name: Call reusable workflow when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy-nox.yaml@main
    with:
      app_name: static-rdf-server
      caller_sha: ${{ github.sha }}
      repo: ${{ github.repository }}
      actor: ${{ github.actor }}
      python_version: '3.9'
      python_architecture: x64
      environment: staging
      cluster: digdir-fdk-dev
      nox_image: True
      nox_env: True
      nox_env_name: API_KEY
      run_safety: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOX_ENV_VALUE: ${{ secrets.TEST_API_KEY }}
