name: Deploy to production & demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-server:
    name: Deploy server to prod on merge to main branch
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy-nox.yaml@main
    with:
      app_name: static-rdf-server
      python_version: "3.10"
      python_architecture: x64
      node_version: 16
      environment: prod
      cluster: digdir-fdk-prod
      nox_image: True
      nox_env: 1
      nox_env_1_name: API_KEY
      snapshot_disk: fdk-prod-static-rdf-server
      snapshot_name: autodeploy-prod-static-rdf-server
      snapshot_zone: europe-north1-a
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOX_ENV_1_VALUE: ${{ secrets.TEST_API_KEY }}

  deploy-server-to-demo:
    needs: build-and-deploy-server
    name: Deploy server to demo if prod-deploy is successful
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy.yaml@main
    with:
      app_name: static-rdf-server
      environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-and-deploy-nginx:
    name: Deploy to nginx prod on merge to main branch
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy-nox.yaml@main
    with:
      app_name: static-rdf-nginx
      python_version: "3.10"
      python_architecture: x64
      environment: prod
      cluster: digdir-fdk-prod
      nox_env: 1
      nox_env_1_name: API_KEY
      nox_cmd: "-s contract_tests"
      dockerfile_context: ./nginx/
      dockerfile: ./nginx/Dockerfile
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOX_ENV_1_VALUE: ${{ secrets.TEST_API_KEY }}

  deploy-nginx-to-demo:
    needs: build-and-deploy-nginx
    name: Deploy nginx to demo if prod-deploy is successful
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy.yaml@main
    with:
      app_name: static-rdf-nginx
      environment: demo
      cluster: digdir-fdk-dev
    secrets:      
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
